version: '2'
services:
 transmission:
  image: nilayparikh/openvpn-proxy:latest
  cap_add:
    - NET_ADMIN
  devices:
    - /dev/net/tun
  restart: always
  ports:
    - "15155:8888"
  dns:
    - 8.8.8.8
    - 8.8.4.4
  environment:
    - OPENVPN_PROVIDER=PIA
    - OPENVPN_CONFIG=US California
    - OPENVPN_USERNAME=x5707644
    - OPENVPN_PASSWORD=tCs8T9xDpG
    - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
    - LOCAL_NETWORK=192.168.2.0/24